### ISSUE TITLE
Add MIT license

### ISSUE THREAD

**Issue by SignpostMarv** [sleddog/chess#10]
the repo [probably needs a license](https://choosealicense.com/)

**Comment by sleddog** [comment]
Agreed.  Can you add the MIT license?

**Comment by Rishabh04-02** [comment]
I want to do it.

**Comment by vaibhavsingh97** [comment]
claiming

**Comment by brandsjek** [comment]
oh, I just PR'ed this exactly the same moment that @SignpostMarv did it. Ignore me please!

**Comment by SignpostMarv** [comment]
@Flippylosaurus I alt-tabbed back here and saw all the comments come in at the same time the branch went up :P
