### ISSUE TITLE
White Qc5+ should be checkmate

### ISSUE THREAD

**Issue by sleddog** [sleddog/chess#2]
From FEN:
http://www.devingray.com/chess/?fen=rnb5%2F1pppn3%2Fp1k1pp1p%2F7Q%2F1PB1P3%2F2P5%2FP1P2PPP%2F3R1RK1%20w%20KQkq%20-%200%2014

White Qc5+ should be checkmate, but doesn't on clientside.

**Comment by dbsmash** [comment]
This is addressed in https://github.com/sleddog/chess/pull/4
