### ISSUE TITLE
Black Doesn't move

### ISSUE THREAD

**Issue by CalderWhite** [sleddog/chess#24]
I was just playing around on [the hosted website](http://www.devingray.com/chess/) and I noticed the user isn't forced to wait for black to move. Thus if the client send quick, consecutive requests all of black's moves return at once.

**Comment by sleddog** [comment]
Thanks for writing this up

**Comment by CalderWhite** [comment]
@sleddog , trying to fix it now! Just looking through the code to get a better understanding.

**Comment by sleddog** [comment]
thanks @CalderWhite
