### ISSUE TITLE
Add sound to the chess move

### ISSUE THREAD

**Issue by sleddog** [sleddog/chess#27]
After a chess move, it would be nice to hear the piece "click" or "thud" of the chess piece being dropped on the board.

This ticket would simply be to add a noise like this to the end of the move.

**Comment by SignpostMarv** [comment]
one assumes you'd want an audio clip, not something as daft as this 😛 :

```html
<button>Thud</button>
<script>
let btn = document.body.childNodes[0];
btn.onclick = () => {
    speechSynthesis.speak(
        new SpeechSynthesisUtterance(btn.textContent)
    );
}
</script>
```

**Comment by ohvitorino** [comment]
Hi! This is a simple one, I'll give you a hand.
Do you want to host the sample sound, or can it be a external resource?

**Comment by ohvitorino** [comment]
I ended up adding the sound file as a resource of the project.

**Comment by SignpostMarv** [comment]
@ohvitorino friday's daft suggestion aside, the speech synthesis api may be useful in having an audio play-by-play of the moves in a game.

**Comment by ohvitorino** [comment]
@SignpostMarv well, it's actually a quite cool feature I guess :) I ended up adding it.
